spring.application.name=BobEsponja
#En spring profiles... se deb de poner los nombrew puesto en el @profile
#Ejemplo spring.profiles.active=mysql,otro
spring.profiles.active=mysql
server.error.include-message=always
